version: '3.7'

services:
  app:
    image: ${AUTHOR}/${PROJECT}:app
    container_name: ${PROJECT}-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www
      - dependencies:/var/www/vendor
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - app-network

  webserver:
    image: nginx:1.17.4-alpine
    container_name: ${PROJECT}-webserver
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
      - app
    networks:
      - app-network

  db:
    image: postgres:12.0
    container_name: ${PROJECT}-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

volumes:
  dependencies:
    driver: local
  dbdata:
    driver: local

networks:
  app-network:
    driver: bridge
